/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.io.*;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

    public String privilege, userEmail;
    public static User user;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Home(User userObj) {
        initComponents();
        setLocationRelativeTo(null);
        userEmail = userObj.getEmail();
        privilege = userObj.getPrivilegeLevel();
        user = userObj;
        if (!privilege.equals("Admin")) {
            btnManageCategory.setVisible(false);
            btnAddNewProduct.setVisible(false);
            btnViewEditDeleteProduct.setVisible(false);
            btnVerifyUser.setVisible(false);
        }
    }

//    private void writeObject(ObjectOutputStream stream) throws IOException{
//        stream.defaultWriteObject();
//    }
//    private void readObject(ObjectInputStream stream) throws IOException, ClassNotFoundException{
//        stream.defaultReadObject();
//    }
//    public Home(boolean status) {
//        initComponents();
//        if (!status) {
//            btnManageCategory.setVisible(false);
//            btnAddNewProduct.setVisible(false);
//            btnViewEditDeleteProduct.setVisible(false);
//            btnVerifyUser.setVisible(false);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLougout = new javax.swing.JButton();
        btnBillnOrderPlacedDetails = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnChangeSecurityQuestion = new javax.swing.JButton();
        btnManageCategory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAddNewProduct = new javax.swing.JButton();
        btnViewEditDeleteProduct = new javax.swing.JButton();
        btnVerifyUser = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Component.borderColor"));
        setMaximumSize(new java.awt.Dimension(1370, 770));
        setMinimumSize(new java.awt.Dimension(1370, 770));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1370, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLougout.setBackground(new java.awt.Color(153, 153, 153));
        btnLougout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLougout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btnLougout.setText("Logout");
        btnLougout.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        btnLougout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLougout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLougoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLougout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 120, -1));

        btnBillnOrderPlacedDetails.setBackground(new java.awt.Color(204, 204, 204));
        btnBillnOrderPlacedDetails.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBillnOrderPlacedDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/View Bills & Order Placed Details.png"))); // NOI18N
        btnBillnOrderPlacedDetails.setText("View Bill & Order Placed Details");
        btnBillnOrderPlacedDetails.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        btnBillnOrderPlacedDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBillnOrderPlacedDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillnOrderPlacedDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBillnOrderPlacedDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 300, -1));

        btnChangePassword.setBackground(new java.awt.Color(153, 153, 153));
        btnChangePassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/change Password.png"))); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        btnChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, -1));

        btnChangeSecurityQuestion.setBackground(new java.awt.Color(204, 204, 204));
        btnChangeSecurityQuestion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChangeSecurityQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/change Security Question.png"))); // NOI18N
        btnChangeSecurityQuestion.setText("Change Security Question");
        btnChangeSecurityQuestion.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        btnChangeSecurityQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSecurityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 270, -1));

        btnManageCategory.setBackground(new java.awt.Color(153, 153, 153));
        btnManageCategory.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/category.png"))); // NOI18N
        btnManageCategory.setText("Manage Category");
        btnManageCategory.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.MatteBorder(null)));
        btnManageCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, 210, -1));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 70, -1));

        btnAddNewProduct.setBackground(new java.awt.Color(204, 204, 204));
        btnAddNewProduct.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new product.png"))); // NOI18N
        btnAddNewProduct.setText("New Product");
        btnAddNewProduct.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.MatteBorder(null)));
        btnAddNewProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, 160, -1));

        btnViewEditDeleteProduct.setBackground(new java.awt.Color(204, 204, 204));
        btnViewEditDeleteProduct.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewEditDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnViewEditDeleteProduct.setText("View, Edit OR Delete Product");
        btnViewEditDeleteProduct.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.MatteBorder(null)));
        btnViewEditDeleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewEditDeleteProduct.setMaximumSize(new java.awt.Dimension(201, 37));
        btnViewEditDeleteProduct.setMinimumSize(new java.awt.Dimension(201, 37));
        btnViewEditDeleteProduct.setPreferredSize(new java.awt.Dimension(201, 37));
        btnViewEditDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEditDeleteProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEditDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 690, 260, -1));

        btnVerifyUser.setBackground(new java.awt.Color(153, 153, 153));
        btnVerifyUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerifyUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/verify users.png"))); // NOI18N
        btnVerifyUser.setText("Verify Users");
        btnVerifyUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.MatteBorder(null)));
        btnVerifyUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerifyUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, -1, -1));

        btnPlaceOrder.setBackground(new java.awt.Color(153, 153, 153));
        btnPlaceOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/place order.png"))); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.MatteBorder(null)));
        btnPlaceOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLougoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLougoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            new Login().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btnLougoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the application?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(a);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnManageCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCategoryActionPerformed
        // TODO add your handling code here:
        new ManageCategory(user).setVisible(true);
    }//GEN-LAST:event_btnManageCategoryActionPerformed

    private void btnAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProductActionPerformed
        // TODO add your handling code here:
        new AddNewProduct(user).setVisible(true);
    }//GEN-LAST:event_btnAddNewProductActionPerformed

    private void btnVerifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyUserActionPerformed
        // TODO add your handling code here:
        new VerifyUser(user).setVisible(true);
    }//GEN-LAST:event_btnVerifyUserActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        new PlaceOrder(user).setVisible(true);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnBillnOrderPlacedDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillnOrderPlacedDetailsActionPerformed
        // TODO add your handling code here:
        new ViewBillOrderPlacedDetails(user).setVisible(true);
    }//GEN-LAST:event_btnBillnOrderPlacedDetailsActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        new ChangePassword(user).setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnChangeSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeSecurityQuestionActionPerformed
        // TODO add your handling code here:
        new ChangeSecurityQuestion(user).setVisible(true);
    }//GEN-LAST:event_btnChangeSecurityQuestionActionPerformed

    private void btnViewEditDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditDeleteProductActionPerformed
        // TODO add your handling code here:
        new ViewEditDeleteProduct(user).setVisible(true);
    }//GEN-LAST:event_btnViewEditDeleteProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewProduct;
    private javax.swing.JButton btnBillnOrderPlacedDetails;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeSecurityQuestion;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLougout;
    private javax.swing.JButton btnManageCategory;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnVerifyUser;
    private javax.swing.JButton btnViewEditDeleteProduct;
    // End of variables declaration//GEN-END:variables
}
