/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import DataAccessObjects.*;
import common.OpenPDF;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.*;

/**
 *
 * @author prati
 */
public class ViewBillOrderPlacedDetails extends javax.swing.JFrame {

    public static User user;
    /**
     * Creates new form ViewBillOrderPlacedDetails
     */
    public ViewBillOrderPlacedDetails(User userObj) {
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todayDate = sdf.format(date);
        txtFilterByDate.setText(todayDate);
        user = userObj;
    }

    public void tableDetails() {
        String date = txtFilterByDate.getText();
        String incrDecr = (String) ComboBoxChangeOrderByID.getSelectedItem();
        DefaultTableModel dtm = (DefaultTableModel) tblBill.getModel();
        dtm.setRowCount(0);
        if (incrDecr.equals("Increment")) {
            ArrayList<Order> billsList = OrderDataAccessObject.getAllRecordsByIncrement(date);
            Iterator<Order> itr = billsList.iterator();
            while (itr.hasNext()) {
                Order bill = itr.next();
                dtm.addRow(new Object[]{bill.getId(), bill.getName(), bill.getMobileNumber(), bill.getEmail(), bill.getDate(), bill.getTotal(), bill.getCreatedBy()});
            }
        } else {
            ArrayList<Order> billsList = OrderDataAccessObject.getAllRecordsByDecrement(date);
            Iterator<Order> itr = billsList.iterator();
            while (itr.hasNext()) {
                Order bill = itr.next();
                dtm.addRow(new Object[]{bill.getId(), bill.getName(), bill.getMobileNumber(), bill.getEmail(), bill.getDate(), bill.getTotal(), bill.getCreatedBy()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        txtFilterByDate = new javax.swing.JTextField();
        ComboBoxChangeOrderByID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1370, 770));
        setMinimumSize(new java.awt.Dimension(1370, 770));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/View Bills & Order Placed Details.png"))); // NOI18N
        jLabel1.setText("View Bills & Order Placed Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Filter By Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Change Order By Total ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 71, -1, -1));

        tblBill.setBackground(java.awt.SystemColor.activeCaption);
        tblBill.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Email", "Date", "Total", "GeneratedBy"
            }
        ));
        tblBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBill);
        if (tblBill.getColumnModel().getColumnCount() > 0) {
            tblBill.getColumnModel().getColumn(0).setHeaderValue("ID");
            tblBill.getColumnModel().getColumn(1).setHeaderValue("Name");
            tblBill.getColumnModel().getColumn(2).setHeaderValue("Mobile Number");
            tblBill.getColumnModel().getColumn(3).setHeaderValue("Email");
            tblBill.getColumnModel().getColumn(4).setHeaderValue("Date");
            tblBill.getColumnModel().getColumn(5).setHeaderValue("Total");
            tblBill.getColumnModel().getColumn(6).setHeaderValue("GeneratedBy");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 1358, -1));

        txtFilterByDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFilterByDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterByDateKeyReleased(evt);
            }
        });
        getContentPane().add(txtFilterByDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 99, 250, -1));

        ComboBoxChangeOrderByID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ComboBoxChangeOrderByID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Increment", "Decrement" }));
        ComboBoxChangeOrderByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxChangeOrderByIDActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxChangeOrderByID, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 99, 250, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("*Click on row to open bill.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 300, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtFilterByDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterByDateKeyReleased
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_txtFilterByDateKeyReleased

    private void ComboBoxChangeOrderByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxChangeOrderByIDActionPerformed
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_ComboBoxChangeOrderByIDActionPerformed

    private void tblBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillMouseClicked
        // TODO add your handling code here:
        int index = tblBill.getSelectedRow();
        TableModel model = tblBill.getModel();
        String id = model.getValueAt(index, 0).toString();
        OpenPDF.openById(id);
    }//GEN-LAST:event_tblBillMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBillOrderPlacedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBillOrderPlacedDetails(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxChangeOrderByID;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtFilterByDate;
    // End of variables declaration//GEN-END:variables
}
